version: "3.4"

services:
  mskcatalogdb:
    container_name: mskcatalogdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"

  mskbasketdb:
    container_name: mskbasketdb
    restart: always
    ports:
      - "6379:6379"

  mskorderdb:
    container_name: mskorderdb
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "z6NAc!Njv-WV"
      ACCEPT_EULA: "Y"

  mskrabbitmq:
    container_name: mskrabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  msk.catalog.api:
    container_name: mskcatalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://mskcatalogdb:27017"
    depends_on:
      - mskcatalogdb
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8000:80"

  msk.basket.api:
    container_name: mskbasketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=mskbasketdb:6379"
      - "EventBus:HostName=mskrabbitmq"
    depends_on:
      - mskbasketdb
      - mskrabbitmq
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8001:80"

  msk.ordering.api:
    container_name: mskorderingapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnection=Server=mskorderdb;Database=OrderDb;User Id=sa;Password=z6NAc!Njv-WV;"
      - "EventBus:HostName=mskrabbitmq"
    depends_on:
      - mskorderdb
      - mskrabbitmq
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8002:80"

  msk.apigateway:
    container_name: mskapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - msk.catalog.api
      - msk.basket.api
      - msk.ordering.api
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "7000:80"
