version: "3.4"

services:
  mskcatalogdb:
    container_name: mskcatalogdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"

  mskbasketdb:
    container_name: mskbasketdb
    restart: always
    ports:
      - "6379:6379"

  mskrabbitmq:
    container_name: mskrabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  msk.catalog.api:
    container_name: mskcatalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://mskcatalogdb:27017"
    depends_on:
      - mskcatalogdb
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https
    ports:
      - "8000:80"

  msk.basket.api:
    container_name: mskbasketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=mskbasketdb:6379"
      - "EventBus:HostName=mskrabbitmq"
    depends_on:
      - mskbasketdb
      - mskrabbitmq
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https
    ports:
      - "8001:80"

